title: Where is the grey?
author: Kritzkrieg-Medic
email: Coming soon, is this a link?
description: > # this means to ignore newlines until "baseurl:"
  Why can't we be friends?

social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-dinky
